<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\Usuario\Documents\GitHub\Parcial_2_Automovil.NET\HybridDDDArchitecture\Core.Application.Adapters.Http\IExternalApiClient.cs" Link="IExternalApiClient.cs" />
  </ItemGroup>

</Project>
