<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="UseCases\DummyEntity\**" />
	  <EmbeddedResource Remove="UseCases\DummyEntity\**" />
	  <None Remove="UseCases\DummyEntity\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="ApplicationServices\DummyEntityApplicationService.cs" />
	  <Compile Remove="ApplicationServices\IDummyEntityApplicationService.cs" />
	  <Compile Remove="DomainEvents\DummyEntityCreated.cs" />
	  <Compile Remove="DomainEvents\DummyEntityDeleted.cs" />
	  <Compile Remove="DomainEvents\DummyEntityUpdated.cs" />
	  <Compile Remove="Integrations\Events\DummyEntityCreatedIntegrationEvent.cs" />
	  <Compile Remove="Integrations\Events\DummyExternalIntegrationEvent.cs" />
	  <Compile Remove="Integrations\Handlers\Publishers\DummyEntityCreatedIntegrationEventHandlerPub.cs" />
	  <Compile Remove="Integrations\Handlers\Subscribers\DummyEntityCreatedIntegrationEventHandlerSub.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Application.Adapters\Core.Application.Adapters.Http.csproj" />
		<ProjectReference Include="..\Core.Application.ComandQueryBus\Core.Application.ComandQueryBus.csproj" />
		<ProjectReference Include="..\Core.Application.EventBus\Core.Application.EventBus.csproj" />
		<ProjectReference Include="..\Core.Application.Mapping\Core.Application.Mapping.csproj" />
		<ProjectReference Include="..\Core.Application.Repositories\Core.Application.Repositories.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Adapters\" />
		<Folder Include="ApplicationServices\" />
		<Folder Include="DomainEvents\" />
		<Folder Include="Integrations\Events\" />
		<Folder Include="Integrations\Handlers\Publishers\" />
		<Folder Include="Integrations\Handlers\Subscribers\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
	</ItemGroup>

</Project>
